### ISSUE TITLE
User can't delete account

### ISSUE THREAD

**Issue by UltraViolet33** [marceloxhenrique/MyTalk#37]
No way to delete the user account

**Comment by marceloxhenrique** [comment]
@UltraViolet33, I understand how important it is for users to have control over their account, including the ability to delete it. Also being in under the GDPR regulations. Thank you for bring it up, I will prioritize this issue and keep you updated.

**Comment by marceloxhenrique** [comment]
Issue Resolved: Added the requested `DeleteAccount` functionality.
The feature has been tested and is working as expected. For details on the implementation, please refer to PR #41 and PR #42.
Please feel free to create any other issues that you think are relevant to the app. 😃
