### ISSUE TITLE
npm run migration failed

### ISSUE THREAD

**Issue by UltraViolet33** [marceloxhenrique/MyTalk#39]
npm run migration returns:

`npm error Missing script: "migration"

npm error
npm error Did you mean this?
npm error   npm run migrate # run the "migrate" package script
npm error
npm error To see a list of scripts, run:
npm error   npm run`

**Comment by marceloxhenrique** [comment]
Hey @UltraViolet33,

Thank you for bringing this issue to my attention. I will attempt to reproduce the error on my end to identify the cause and work on a solution. I'll keep you updated on the progress.

Thanks again for your feedback!

**Comment by marceloxhenrique** [comment]
Issue Resolved: Fix the script  "migration" in package.json. The script has been tested and is working as expected.
Please note that the database can't be accessed by other users while the migration is running.
For details on the implementation, please refer to PR #43 .
